#!/usr/bin/env bash
echo "== Excluindo bucket"

#lembrar de usar chmod u+x local do arquivo ou pasta
# verifica se algum nome foi informado | o -z verifica se a string é valida ou existe
if [ -z "$1" ]; then
    echo "Nome do bucket não informado"
    exit 1
fi

BUCKET_NAME=$1
#https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
aws s3api delete-bucket \
--bucket $BUCKET_NAME \

